# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" 
    directories:
      - "/packages/sv-ui",
      - "/packages/api",
      - "/apps/web",
      - "/apps/wahlen"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "14:00"
      timezone: "Europe/Berlin"
    assignees:
      - "dependabot"
    commit-message:
      prefix: "MAIN-DEP: "
    labels:
      - "dependencies"
    open-pull-requests-limit: 4
    pull-request-branch-name:
      seperator: "-"
    reviewers:
      - "jackatdjl"
    target-branch: 
      - "main"
      - "v*.*.*"
  - package-ecosystem: "npm" 
    directories:
      - "/packages/sv-ui",
      - "/packages/api",
      - "/apps/web",
      - "/apps/wahlen"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Berlin"
    assignees:
      - "dependabot"
    commit-message:
      prefix: "MAIN-DEP: "
    labels:
      - "dependencies"
    open-pull-requests-limit: 4
    pull-request-branch-name:
      seperator: "-"
    reviewers:
      - "jackatdjl"
    target-branch: "v*.*.*-dev"
