cacheFolder: ./.yarn/cache

cacheMigrationMode: match-spec

checksumBehavior: throw

cloneConcurrency: 2

compressionLevel: 3

defaultProtocol: "npm:"

enableColors: true

enableConstraintsChecks: true

enableGlobalCache: true

enableProgressBars: true

enableTimers: true

globalFolder: ../.yarn/berry

nodeLinker: node-modules

pnpMode: loose

progressBarStyle: jack

winLinkType: symlinks

yarnPath: .yarn/releases/yarn-4.5.3.cjs
