# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches: ["main", "v*.*.*"]
  pull_request:
    branches: ["main", "v*.*.*"]
  schedule:
    - cron: "0 14 * * 1"
    - cron: "0 14 * * 3"
    - cron: "0 10 * * 6"

jobs:
  eslint:
    strategy:
      matrix:
        directory:
          ["/packages/sv-ui", "/packages/api", "/apps/wahlen", "/apps/web"]
    name: Run Eslint Scanning for ${{ matrix.directory }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move to ${{ matrix.directory }} directory
        run: cd ${{ matrix.directory }}

      - name: Install Formatter
        run: |
          yarn add @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: yarn dlx eslint .
          --config config.eslint.mjs
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
